export const familyMembers = {
  close: {
    minor: [
      "mother",
      "stepmother",
      "father",
      "stepfather",
      "sister",
      "stepsister",
      "brother",
      "stepbrother",
    ],
    adult: ["son", "daughter", "partner", "childhood best friend"],
  },
  distant: {
    minor: ["cousin", "aunt", "uncle", "grandma", "grandpa"],
    adult: [
      "nephew",
      "niece",
      "mother-in-law",
      "father-in-law",
      "sister-in-law",
      "brother-in-law",
      "ex-partner",
    ],
  },
};

export const residence = {
  adjective: [
    "a quiet",
    "a central",
    "a dark and cold",
    "a warm and sunny",
    "medieval",
    "a remote",
    "a noisy",
    "a beautiful",
    "an industrial",
    "a peaceful",
    "the most beautiful",
    "a small",
    "a deserted",
    "a lively",
    "a big",
    "an enormous",
    "a vibrant",
    "a hectic",
    "a famous",
    "a mysterious",
    "a popular",
    "a boring",
    "a haunted",
    "a polemic",
    "the cutest",
    "a cozy",
    "an ugly, but cozy",
    "a modern",
    "an old",
    "an antique",
  ],
  place: [
    "town",
    "palace",
    "bungalow",
    "alley",
    "hotel",
    "motel",
    "beach house",
    "basement",
    "penthouse",
    "parking lot",
    "forest",
    "monastery",
    "castle",
    "lodge",
    "tiny house",
    "city",
    "village",
    "neighborhood",
    "suburb",
    "apartment block",
    "street",
    "square",
    "house",
    "house on a hill",
    "apartment",
    "flat",
    "room",
    "attic",
    "farmhouse",
    "mansion on a hill",
    "house on the countryside",
    "coastal village",
    "business district",
  ],
};
