export const schoolExperience = {
  child: {
    subjects: [
      "Reading & Writing",
      "Physical Education",
      "History",
      "Geography",
      "Science",
      "Music",
      "Arts",
      "Mathematics & Numbers",
    ],
    experience: [
      "fun",
      "dull",
      "boring",
      "exciting",
      "pretty cool",
      "useful",
      "alright",
      "okay",
      "the best",
      "awesome",
      "nice",
      "the best place to make friends",
    ],
  },
  teenager: {
    subjects: [
      "Language & Literature",
      "Mathematics",
      "Chemistry",
      "Physics",
      "Biology",
      "Geography",
      "History",
      "French",
      "Spanish",
      "Chinese",
      "Philosophy",
      "Drama",
      "Classical Languages",
      "Physical Education",
      "Social Science",
    ],
    experience: [
      "the best",
      "hell",
      "a total prison",
      "a disaster",
      "an interesting place",
      "the path towards a bright future",
      "a necessary evil",
      "alright",
      "fun",
      "a great opportunity to explore oneself",
      "the worst",
      "useless",
      "useful",
      "a nest of snakes",
      "a beehive",
      "awesome",
      "a social safety net",
    ],
    afterSchoolActivities: {
      classic: [
        "acts as the unofficial leader of Debate Club",
        "works as a Student Ambassador",
        "is an enthusiastic member of the Party Committee",
        "is a serial champion of the school's Math League",
        "recently became editor for the School Newspaper",
        "is Head of Drama Club",
        "volunteers for the school's tutoring network",
        "is the star of the hockey team",
        "works as a library assistant",
        "is Secretary of the Student Union",
        "is a Maths tutor",
        "works as a Latin tutor",
        "volunteers as a buddy for foreign students",
        "is a student member of the Education Committee",
        "is President of the Student Council",
        "founded Science Club",
        "earns some extra cash working as a babysitter for the neighbors",
        "volunteers at the local animal shelter",
        "works as a petsitter",
        "volunteers at the Community Center",
        "earns some extra money as a mail carrier",
        "works as a dog walker",
        "works as a dishwasher at a restaurant three evenings a week",
        "coaches the juniors of the school's soccer team",
      ],
      modern: [
        "secretly deals marijuana in the school's bathroom",
        "runs a successful study blog",
        "participates in Model U.N.",
      ],
    },
  },
};

export const studies = {
  classic: [
    "Accounting",
    "Agriculture",
    "Anthropology",
    "Archaeology",
    "Architecture",
    "Art & Design",
    "Art History",
    "Arts & Humanities",
    "Biochemistry",
    "Biology",
    "Business Management",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Classical Studies",
    "Creative Writing",
    "Criminology",
    "Dentistry",
    "Economics",
    "Electronic Engineering",
    "Fashion",
    "Finance",
    "Geography",
    "Geology",
    "History",
    "Journalism",
    "Languages",
    "Law",
    "Linguistics",
    "Literature",
    "Marine Biology",
    "Mathematics",
    "Mechanical Engineering",
    "Medicine",
    "Music",
    "Nursing & Health Care",
    "Optrometry",
    "Pharmacology & Pharmacy",
    "Philosophy",
    "Physics",
    "Physiotherapy",
    "Political Science",
    "Psychology",
    "Sociology",
    "Theatre",
    "Theology",
    "Veterinary Medicine",
    "Zoology",
    "Public Administration",
    "Public Relations",
    "Restaurant Management",
    "Sales",
    "Social Work",
    "Special Education",
    "Statistiscs",
    "Welding Technology",
    "Agricultural Engineering",
    "Aircraft Mechanics",
    "Animal Sciences",
    "Automotive Technology",
    "Behavioral Sciences",
    "Bio-engineering",
    "Biomedical Science",
    "Carpentry",
    "Criminal Justice",
    "Culinary Art",
    "Electrical Technology",
    "Ethnic Studies",
    "Forensics",
    "International Relations",
    "Liberal Arts",
    "Military Technologies",
    "Music",
    "Nutrition",
    "Operations Management",
    "Ecology",
    "Education",
    "Industrial Mechanics",
    "Gender Studies",
  ],
  modern: [
    "Communications",
    "Food Science",
    "Film",
    "Game Design",
    "Media Studies",
    "Tourism",
    "Robotics",
    "Software Engineering",
    "Computer Science",
    "Marketing",
    "Environmental Studies",
    "Aeronautical Engineering",
    "Medical Technology",
    "Sports Science",
    "Advertising",
    "Education Sciences",
    "Cyber Security",
    "Digital Media Creation",
    "Hospitality Management",
    "Hotel Management",
    "Human Resources",
    "Information Systems Management",
    "Information Technology",
    "Photography",
    "Programming",
  ],
  experience: [
    "turned out to be a great choice",
    "was the safest choice of all",
    "was a good opportunity to escape from home",
    "was the worst decision ever",
    "is a total waste of time",
    "has been torture so far",
    "is supposed to be the ticket to a successful career",
    "is kinda boring",
    "is super exciting",
    "is alright",
    "was an expensive mistake",
    "turned out to be way harder than expected",
    "turned out to be much easier than expected",
    "was Dad's wish",
    "was Mom's wish",
    "is all paid for by Grandma",
    "is better than doing nothing all day",
    "is better than being stuck in a dead-end job",
    "sucks",
    "rocks",
    "was a choice of heart rather than sense",
    "could very well be the road towards unemployment",
    "promises great career perspectives",
    "costs a fortune",
    "is a shortcut to infinite wealth",
  ],
};

export const jobs = {
  classic: {
    fullTimeJobs: [
      "a baker",
      "a barber",
      "a builder",
      "a bus driver",
      "a businessperson",
      "a butcher",
      "a car mechanic",
      "a cashier",
      "a chef",
      "a cleaner",
      "a detective",
      "a film director",
      "a doctor",
      "a farmer",
      "a fighter pilot",
      "a firefighter",
      "a flight attendant",
      "a hairdresser",
      "a judge",
      "a mail carrier",
      "a make-up artist",
      "a manager",
      "a miner",
      "a musician",
      "a nurse",
      "a pharmacist",
      "a pilot",
      "a plumber",
      "a police officer",
      "a professional golf player",
      "a professional soccer player",
      "a professor",
      "a reporter",
      "a sailor",
      "a scientist",
      "a server",
      "a soldier",
      "a surgeon",
      "a taxi driver",
      "a teacher",
      "a tour guide",
      "a vet",
      "a writer",
      "an architect",
      "an artist",
      "an astronaut",
      "an astronomer",
      "an office worker",
      "an optician",
      "a construction manager",
      "a cosmetologist",
      "a dental hygienist",
      "a dentist",
      "a journalist",
      "a kindergarten teacher",
      "a marine mechanic",
      "a massage therapist",
      "a newspaper editor",
      "a paralegal",
      "a pharmacy technician",
      "a physical therapist",
      "a psychologist",
      "a realtor",
      "a welder",
      "an actor",
      "an aircraft mechanic",
      "an electrician",
      "a security guard",
      "a sports coach",
      "a music teacher",
      "a translator",
    ],
    sideJobs: [
      "a server",
      "a bartender",
      "a cashier at the local store",
      "a volunteer at the local animal shelter",
      "a sales assistant at a clothing store",
      "a sales assistant at a pet store",
      "a lifeguard",
      "a house cleaner",
      "a tour guide",
      "a music tutor",
      "a language tutor",
      "a maths tutor",
      "a science tutor",
      "a housesitter",
      "a dog walker",
      "a gardener",
      "a lawn mower",
      "a music teacher",
      "a sports coach",
      "a street performer",
      "an entertainer at children's birthday parties",
      "a part-time nanny",
      "a security guard",
      "a freelance translator",
    ],
  },
  modern: {
    fullTimeJobs: [
      "a computer programmer",
      "a photographer",
      "an account manager",
      "a videogames designer",
      "a web developer",
      "an influencer",
      "a tech guru",
      "a life coach",
      "a career coach",
      "a graphic designer",
      "a computer technician",
      "a copywriter",
      "a social media manager",
      "a digital content creator",
    ],
    sideJobs: [
      "a call center agent",
      "a food delivery person",
      "a parcel delivery person",
      "freelance web designer",
      "freelance photographer",
      "an influencer",
      "a rideshare driver",
      "a vlogger",
      "a blogger",
      "a film and TV extra",
      "an online English teacher",
      "a freelance copywriter",
      "a virtual assistant",
    ],
  },
  experience: [
    "was a bit disappointing",
    "wasn't an easy road",
    "was a rocky road",
    "pays incredibly well",
    "pays the bills",
    "is the most fulfilling job ever",
    "is a dream come true",
    "could have ended worse",
    "wasn't what Mom and Dad expected",
    "is a very rewarding job",
    "came as a total surprise to a lot of people",
    "isn't too bad",
    "was always the plan",
    "is just a temporary solution",
    "is a necessary evil to pay the bills",
    "is no one's dream job, but well",
    "is what everybody dreams of",
    "is something to be proud of",
    "couldn't have been more ironic",
    "is absolutely dreadful",
    "was Dad's lifelong dream",
    "was Mom's lifelong dream",
    "is a bit embarrassing",
  ],
};
