export const hobbies = {
  classic: {
    general: [
      "playing soccer",
      "playing football",
      "surfing",
      "playing tennis",
      "pulling pranks",
      "knitting",
      "sewing",
      "making jewelry",
      "hiking",
      "baking",
      "playing basketball",
      "gossiping",
      "woodworking",
      "listening to music",
      "kickboxing",
      "dancing",
      "drawing",
      "painting",
      "reading",
      "writing",
      "singing",
      "swimming",
      "playing the guitar",
      "playing the piano",
      "playing the violin",
      "traveling",
      "playing board games",
      "writing letters to pen pals",
      "cycling",
      "star gazing",
      "daydreaming",
      "making pottery",
      "scrapbooking",
      "journaling",
      "acting",
      "flower pressing",
      "cooking",
      "gardening",
      "visiting museums",
      "solving crossword puzzles",
      "learning languages",
      "writing postcards",
      "collecting stamps",
      "collecting sea shells",
    ],
    child: [
      "playing outside",
      "going to the playground",
      "running in the woods",
      "building tree houses",
      "climbing trees",
      "catching bugs",
      "playing hide and seek",
      "collecting stickers",
      "building with blocks",
    ],
    teenager: [
      "cheerleading",
      "getting good grades",
      "studying",
      "sleeping",
      "going shopping with Mom's money",
      "experimenting with sex",
      "hanging with friends",
      "experimenting with alcohol",
      'avoiding parents and other "adults"',
      "going to parties",
      "hanging out at the park",
      "grooming horses at the barn",
    ],
    adult: [],
    senior: [],
  },
  modern: {
    general: [
      "watching TV",
      "rollerblading",
      "blogging",
      "vlogging",
      "making videos",
      "creating podcasts",
      "coding",
      "making music with the band",
    ],
    child: ["new hobby"],
    teenager: ["going to the mall", "texting"],
    adult: [],
    senior: [],
  },
};

export const interests = {
  food: [
    "pasta",
    "fruit",
    "vegetables",
    "cheese",
    "candy",
    "burgers",
    "pizza",
    "chocolate",
    "ham",
    "chicken soup",
  ],
  toys: [
    "cat",
    "dog",
    "rabbit",
    "guinea pig",
    "hamster",
    "teddy bear",
    "magic kit",
    "ribbons",
    "dolls",
    "stickers",
    "coloring book",
    "cars",
    "action figures",
    "Barbie dolls",
    "plastic insects",
    "train set",
    "make-up set",
    "bike",
    "marbles",
    "microscope",
    "binoculars",
    "chemistry kit",
    "trampoline",
    "miniature airplane",
    "football",
    "kite",
    "rubber ducky",
    "pencils",
    "watercolor set",
    "crayons",
    "mini kitchen",
    "balloons",
    "wooden puzzles",
    "bow and arrow",
    "caution tape",
    "dress-up outfits",
    "princess dress",
    "pirate costume",
    "watergun",
    "beads",
    "art kit",
  ],
  classic: {
    general: [
      "nature",
      "fashion",
      "cats",
      "money",
      "drama",
      "technology",
      "psychology",
      "astronomy",
      "astrology",
      "horoscopes",
      "conspiracy theories",
      "cars",
      "martial arts",
      "bowling",
      "make-up",
      "dogs",
      "the outdoors",
      "crochet",
      "stand-up comedy",
      "classical music",
      "food",
      "sports",
      "science",
      "photography",
      "birds",
      "magic",
      "comics",
      "art",
      "music",
      "horses",
      "calligraphy",
      "origami",
      "sudoku",
      "jigsaw puzzles",
      "poetry",
      "French literature",
      "English literature",
      "Spanish literature",
      "Latin-American literature",
      "Russian literature",
      "American literature",
    ],
    child: [""],
    teenager: [
      "school",
      "politics",
      "girls",
      "boys",
      "cigarettes",
      "clothes",
      "who is dating who",
      "freedom",
      "that ONE teacher",
      "that ONE kid in class",
      "tomorrow's test",
    ],
    adult: [
      "interior design",
      "architecture",
      "religion",
      "spirituality",
      "politics",
      "meditation",
      "wine",
    ],
  },
  modern: {
    general: [
      "cryptocurrencies",
      "videogames",
      "graffiti",
      "old movies",
      "memes",
      "nail art",
      "old music",
      "disco music",
      "golden oldies",
      "horror movies",
      "romantic comedies",
      "science fiction",
      "artificial intelligence",
    ],
    child: [],
    teenager: ["boybands", "social media"],
    adult: ["mindfullness", "yoga"],
  },
};
