export const personalityTypes = [
  {
    personality: "Architect",
    type: "INTJ",
    description:
      "imaginative and strategic thinkers, with a plan for everything",
  },
  {
    personality: "Logician",
    type: "INTP",
    description:
      "innovative inventors with an unquenchable thirst for knowledge",
  },
  {
    personality: "Commander",
    type: "ENTJ",
    description:
      "bold, imaginative and strong-willed leaders, always finding a way – or making one",
  },
  {
    personality: "Debater",
    type: "ENTP",
    description:
      "smart and curious thinkers who cannot resist an intellectual challenge",
  },
  {
    personality: "Advocate",
    type: "INFJ",
    description:
      "quiet and mystical, yet very inspiring and tireless idealists",
  },
  {
    personality: "Mediator",
    type: "INFP",
    description:
      "poetic, kind and altruistic people, always eager to help a good cause",
  },
  {
    personality: "Protagonist",
    type: "ENFJ",
    description:
      "charismatic and inspiring leaders, able to mesmerize their listeners",
  },
  {
    personality: "Campaigner",
    type: "ENFP",
    description:
      "enthusiastic, creative and sociable free spirits, who can always find a reason to smile",
  },
  {
    personality: "Logistician",
    type: "ISTJ",
    description:
      "practical and fact-minded individuals, whose reliability cannot be doubted",
  },
  {
    personality: "Defender",
    type: "ISFJ",
    description:
      "very dedicated and warm protectors, always ready to defend their loved ones",
  },
  {
    personality: "Executive",
    type: "ESTJ",
    description:
      "excellent administrators, unsurpassed at managing things – or people",
  },
  {
    personality: "Consul",
    type: "ESFJ",
    description:
      "extraordinarily caring, social and popular people, always eager to help",
  },
  {
    personality: "Virtuoso",
    type: "ISTP",
    description:
      "bold and practical experimenters, masters of all kinds of tools",
  },
  {
    personality: "Adventurer",
    type: "ISFP",
    description:
      "flexible and charming artists, always ready to explore and experience something new",
  },
  {
    personality: "Entrepreneur",
    type: "ESTP",
    description:
      "smart, energetic and very perceptive people, who truly enjoy living on the edge",
  },
  {
    personality: "Entertainer",
    type: "ESFP",
    description:
      "spontaneous, energetic and enthusiastic people – life is never boring around them",
  },
];

export const traits = {
  virtues: [
    "independence",
    "keen eye for detail",
    "patience",
    "generosity",
    "kindness",
    "honesty",
    "resourcefulness",
    "sense of responsibility",
    "wit",
    "charm",
    "charisma",
    "compassion",
    "modesty",
    "integrity",
    "imagination",
    "confidence",
    "strength",
    "beauty",
    "popularity",
    "empathy",
    "energy",
    "loyalty",
    "enthusiasm",
    "courage",
    "sense of humor",
    "intelligence",
    "decisiveness",
    "boldness",
    "devotion",
    "discipline",
    "determination",
    "creativity",
    "openmindedness",
    "optimism",
  ],
  weaknesses: [
    "aloof",
    "impatient",
    "selfish",
    "lazy",
    "narrow-minded",
    "vain",
    "manipulative",
    "rude",
    "greedy",
    "arrogant",
    "jealous",
    "petty",
    "unforgiving",
    "bossy",
    "overly rational",
    "overly emotional",
    "reckless",
    "stubborn",
    "irresponsible",
    "inconsiderate",
    "impulsive",
    "boring",
    "messy",
    "forgetful",
    "demanding",
  ],
  fears: [
    "needles",
    "rejection",
    "coming out",
    "being gay",
    "spiders",
    "heights",
    "narrow spaces",
    "social situations",
    "dogs",
    "roller coasters",
    "clowns",
    "the dark",
    "ending up alone",
    "getting ill",
    "leaving the house",
    "hospitals",
    "the unknown",
    "ghosts",
    "graveyards",
    "churches",
  ],
  insecurities: [
    "nose",
    "hands",
    "feet",
    "hair",
    "arms",
    "legs",
    "nails",
    "teeth",
    "body hair",
    "belly",
    "height",
    "weight",
    "laugh",
    "smile",
    "career prospects",
    "financial situation",
    "past",
    "relationship status",
    "shyness",
    "big mouth",
    "radical behavior",
    "age",
    "allergies",
    "appearance",
    "disability",
    "ethnicity",
    "family situation",
    "freckles",
    "intellectual capabilities",
    "lack of confidence",
    "lack of friends",
    "mental illness",
    "personality",
    "romantic experience",
    "scars",
    "self-doubt",
    "sexual orientation",
    "sexual skills",
    "skin color",
    "social anxiety",
    "social skills",
    "social status",
  ],
  style: [
    "iconic",
    "bold",
    "preppy",
    "colorful",
    "sexy",
    "cute",
    "casual",
    "revealing",
    "dark",
    "dark",
    "sober",
    "fashionable",
    "elegant",
    "geeky",
    "vintage",
    "alternative",
    "frivolous",
    "decent",
    "extravagant",
    "eccentric",
    "classy",
    "comfortable",
    "business casual",
    "sporty",
  ],
  quirks: {
    classic: [
      "often wears different socks",
      "has been wearing the same friendship bracelet for years",
      "likes black nailpolish",
      "enjoys walking in the rain",
      "hates the beach",
      "speaks six languages fluently",
      "loves daydreaming",
      "is curious about the afterlife",
      "has no sense of direction",
      "collects rubber ducks",
      "always chews gum",
      "walks very fast",
      "sleeps with a stuffed toy",
      "cannot stand judgmental people",
      "is left-handed",
      "always loses at boardgames",
      "is obsessed with food",
      "complains a lot about silly things",
      "is always in for an adventure",
      "only listens to instrumental music",
      "finishes other people's sentences",
      "knows everything about medieval history",
      "is good with numbers",
      "has a photographic memory",
      "has a special connection with animals",
      "has an unusually high tolerance for pain",
      "has terrible handwriting",
      "often holds a grudge",
      "is drawn to mirrors",
      "sings in the shower",
      "prefers walking barefoot",
      "always plans everything weeks, months or even years ahead",
      "is always late",
      "has never been to the zoo",
      "dreams of space travel",
      "has never been in love",
      "strongly dislikes babies",
      "is extremely supersticious",
      "only likes cheese when it's melted",
      "is always cold",
      "has several imaginary friends",
      "is vegan",
      "is a vegetarian",
      "doesn't like seafood",
      "is allergic to sunlight",
      "laughs at bad jokes",
      "brags about every accomplishment",
      "is desperate for approval of others",
      "is obsessive about personal hygiene",
      "is overly trusting of other people",
      "has a tendency to take things personally",
      "won't touch other people",
      "has a very contageous laugh",
      "loves being the center of attention",
      "cannot whistle",
      "always orders the same food in restaurants",
      "brings snacks everywhere",
      "cannot throw anything away",
      "tends to interrupt others",
      "has two different eye colors",
      "has a lot of freckles",
      "describes things very precisely",
      "gestures a lot when talking",
      "always insists on having the last word",
      "makes up a nickname for everyone",
      "cares a lot about other people's opinions",
      "wears socks with sandals",
      "always wears a scarf",
      "always carries an umbrella",
      "uses a pocket watch",
      "constantly complains about aches and pains",
      "constantly corrects other people's grammar",
      "frequently gets hiccups",
      "expects unquestioning loyalty from people",
      "is easily influenced",
      "participates in marches and protests",
      "makes snap judgements about other people",
      "seems to turn all conversations political",
      "tends to look for the bright side in every situation",
      "is very ticklish",
      "wears pajamas in public",
      "strongly dislikes change",
      "always roots for the underdog",
      "has no problem telling a white lie every now and then",
      "blushes easily",
      "cries easily",
      "laughs in innapropriate situations",
      "believes in aliens and UFOs",
      "always gets papercuts when reading books",
      "always carries a book",
      "finds comfort in going to Church",
      "is not religious, but loves reading the Bible",
      "needs glasses, but refuses to wear them",
      "doesn't like to eat in front of others",
      "is sensitive to loud noises",
      "is intolerant to lactose",
      "loves writing, but has dyslexia",
      "is a terrible liar",
      "enjoys fire",
      "never learnt to swim",
      "cannot stand odd numbers",
      "has an obsession with symmetry",
      "types with one finger",
      "fidgets out of habit",
      "snores when sleeping",
      "wears a different hairstyle everyday",
      "doesn't leave the house without a bottle of water",
      "doesn't like fruit",
      "strongly believes in Friday the 13th",
      "lights a candle every night before bed",
      "prefers fake flowers to real ones",
      "has two left feet",
      "is terrible at remembering birthdays",
      "always knows what phase the moon is in",
      "unconsciously mispronounces certain words",
      "uses catchphrases a lot",
      "is addicted to tea",
      "cannot ride a bike",
      "loves to draw, but is terrible at it",
      "hates surprises",
      "never goes to parties",
      "overthinks everything",
      "cannot sleep without a fan on",
      "expects to be treated nicely, but treats others terribly",
      "is an encyclopedia of useless facts",
      "swears a lot",
      "always makes up excuses to get out of social obligations",
      "often tries to run away from responsibilities",
      "believes in magic",
      "constantly imitates animal noises",
      "avoids public transport because it's filthy and smells bad",
      "always spots celebrities in random places",
      "doesn't like the taste of water",
      "plans outfits in advance",
      "leaves notes in library books for future readers",
      "often thinks out loud",
      "is not great at managing priorities",
      "is too good at saying no",
      "speaks in a monotone voice",
      "rarely goes outside",
    ],
    modern: [
      "surfs the dark web for inspiration",
      "has a small tattoo of a cat paw",
      "easily obsesses over TV shows",
      "knows the lyrics to every song on the radio",
      "loves watching movies with bad reviews",
      "writes software for fun",
      "would love to try cosplaying",
      "takes a selfie everyday",
      "is obsessed with videogames",
      "always has the newest gadgets",
      "wears cheap knock-offs of designer fashions",
      "quotes oneliners from films and TV shows",
      "is terrified of talking on the phone",
      "wears T-shirts with cartoon characters on them",
    ],
  },
};

export const dreams = [
  "having a big family",
  "building a house",
  "seeing the seven wonders of the world",
  "swimming with sharks",
  "going on a jungle expedition",
  "becoming a millionaire",
  "traveling the world",
  "writing a novel",
  "learning to fly",
  "becoming a CEO",
  "becoming President",
  "moving abroad",
  "starting a small business",
  "being famous",
  "bringing world peace",
  "driving a race car",
  "finding the holy grail",
  "inventing a human cloning machine",
  "living on a deserted island",
  "playing in a successful band",
  "sailing the seven seas",
  "saving the forests",
  "saving the whales",
  "starting a bed and breakfast in Italy",
  "winning an Olympic medal",
];

export const elements = [
  {
    name: "water",
    traits: ["intuitive", "emotional", "calm"],
    symbol: "🜄",
  },
  {
    name: "fire",
    traits: ["passionate", "confident", "bold"],
    symbol: "🜂",
  },
  {
    name: "earth",
    traits: ["practical", "grounded", "reliable"],
    symbol: "🜃",
  },
  {
    name: "air",
    traits: ["intellectual", "curious", "social"],
    symbol: "🜁",
  },
];

export const starSigns = [
  {
    sign: "./img/aries.png",
    name: "Aries",
    element: elements[1],
  },
  {
    sign: "./img/taurus.png",
    name: "Taurus",
    element: elements[3],
  },
  {
    sign: "./img/gemini.png",
    name: "Gemini",
    element: elements[2],
  },
  {
    sign: "./img/cancer.png",
    name: "Cancer",
    element: elements[0],
  },
  {
    sign: "./img/leo.png",
    name: "Leo",
    element: elements[1],
  },
  {
    sign: "./img/virgo.png",
    name: "Virgo",
    element: elements[3],
  },
  {
    sign: "./img/libra.png",
    name: "Libra",
    element: elements[2],
  },
  {
    sign: "./img/scorpio.png",
    name: "Scorpio",
    element: elements[0],
  },
  {
    sign: "./img/sagittarius.png",
    name: "Sagittarius",
    element: elements[1],
  },
  {
    sign: "./img/capricorn.png",
    name: "Capricorn",
    element: elements[3],
  },
  {
    sign: "./img/aquarius.png",
    name: "Aquarius",
    element: elements[2],
  },
  {
    sign: "./img/pisces.png",
    name: "Pisces",
    element: elements[0],
  },
];

export const advice = [
  '"don\'t look at the calendar. Just keep celebrating every day"',
  '"invest in quality pieces, they never go out of style"',
  '"fall in love, get married. Sex is to be encouraged"',
  '"even if you feel hatred, keep it to yourself. Don\'t hurt other people for any reason"',
  '"don\'t ever give up on love"',
  '"nobody else controls you"',
  '"make time to cry"',
  '"travel while you\'re young and able"',
  '"experience is far more valuable than money will ever be"',
  "\"don't compare. You'll never be happy with your life. The grass is always greener\"",
  '"if you are embarrassed to be dating someone, you should not be dating them"',
  '"do one thing each day that is just for you"',
  '"do one thing every day that scares you"',
  '"don\'t be a cheapskate"',
  '"forgive"',
  '"find your passion and live it"',
  '"most time things will figure themselves out"',
  '"choose the right parents"',
  '"have a pet. Life gets lonely sometimes. Pets are reminders of how we\'re all living things"',
  '"take time to mourn what you\'ve lost"',
  '"keep going and never give up"',
  '"make yourself walk"',
  '"you don\'t have to be happy all the time, you need to be satisfied"',
  '"get a great education. That is something that no one can take away from you"',
  '"exercise every morning"',
  '"don\'t die too early"',
  '"just go ahead and do your thing no matter what"',
  '"involve yourself in local problems. There are all sorts of things that have to be tended to in the world"',
  '"just keep going"',
  '"there is no need to ever retire, but if one must, it should be a lot later than 65"',
  '"take the stairs and carry your own stuff"',
  '"pain is mysterious, and having fun is the best way to forget it"',
  '"science alone can\'t help or cure people"',
  "\"you don't know when your number is up, and you can't take it with you to the next place\"",
  '"find a role model and aim to achieve even more than they could ever do"',
  '"don\'t marry an older man, marry a younger one"',
  '"try not to worry. Just try to live"',
  '"have enough trust and confidence in yourself to deal with things as they come"',
  '"keep busy doing what you like"',
  '"humor is a life force, a way of surviving the difficulties of living"',
  '"when you laugh at yourself, you prevent others from laughing at you"',
  '"be curious"',
  '"age is not a disease"',
  '"don\'t get hurt"',
  '"when you are honest with people, it comes back to you, and they are honest with you"',
  '"keep an open mind, and things seem less strange"',
  '"always listen to the other person. You will learn a lot more listening to others than telling them what you know"',
  '"if you find a job you love, you will never have to work a day in your life"',
  '"take naps every day"',
  '"the night is darkest before dawn"',
  '"take the time to look at and appreciate the smaller things that make this life beautiful"',
  '"do something interesting every day; otherwise you disintegrate"',
  '"learning new things makes you happy and keeps your mind active"',
  '"sleep well, try not to worry, and enjoy good dreams"',
  '"be around positive people, people who lift you up, not bring you down"',
  '"mind your own business, and don\'t eat junk food"',
  '"have a good appetite, lots of friends, and keep busy"',
  '"have a good wife, two scotches a night, and be easygoing"',
  '"look inside your soul and find your tools"',
  '"laughter keeps you healthy"',
  '"never run out of responsibility; if you don\'t have one, find one"',
  '"it is very important to have a widespread curiosity about life"',
  '"keep yourself alert, active, and educated"',
  "\"don't smoke, don't drink, and don't retire\"",
  '"take one day at a time, and go along with the tide"',
  '"don\'t analyze it, just do it"',
  '"take it easy, enjoy life, what will be will be"',
  '"have a Bailey\'s Irish Cream before bed if you have a cold — you will wake up fine the next morning"',
];
